site_name: FastAPI Guard Agent
site_description: Reporting Agent for FastAPI Guard. Collects and sends metrics and events from FastAPI Guard.
site_url: https://rennf93.github.io/fastapi-guard-agent/latest/
repo_name: rennf93/fastapi-guard-agent
repo_url: https://github.com/rennf93/fastapi-guard-agent
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark-blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dark-blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/favicon.png

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial:
    - Getting Started: tutorial/getting-started.md
    - Configuration: tutorial/configuration.md
    - Integration: tutorial/integration.md
  - API Reference:
    - Overview: api/overview.md
    - Agent Handler: api/agent-handler.md
    - Event Buffer: api/event-buffer.md
    - Transport: api/transport.md
    - Models: api/models.md
    - Protocols: api/protocols.md
    - Utilities: api/utilities.md
  - Guides:
    - Advanced Configuration: guides/advanced-configuration.md
    - Redis Integration: guides/redis-integration.md
    - Monitoring & Metrics: guides/monitoring.md
    - Troubleshooting: guides/troubleshooting.md
  - Examples: examples/index.md
  - Release Notes: release-notes.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - def_list

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [guard_agent]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            docstring_style: google
            show_if_no_docstring: true
            filters: ["!^_"]
            merge_init_into_class: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rennf93/fastapi-guard-agent
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fastapi-guard-agent/

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by using our
            <a href="https://github.com/rennf93/fastapi-guard-agent/issues/new">issue tracker</a>.

  generator: false
  meta:
    - property: og:type
      content: website
    - property: og:title
      content: FastAPI Guard Agent - Reporting Agent for FastAPI Guard
    - property: og:description
      content: Reporting Agent for FastAPI Guard. Collects and sends metrics and events from FastAPI Guard.
    - property: og:image
      content: https://rennf93.github.io/fastapi-guard-agent/assets/big_logo.svg
    - name: keywords
      content: fastapi, security, middleware, python, ip control, rate limiting, penetration detection

  version:
    provider: mike
    default: latest
    version_selector: true
    json_file: /fastapi-guard-agent/versions.json

  author:
    name: Renzo Franceschini
    url: https://github.com/rennf93

copyright: FastAPI Guard Agent by

extra_css:
  - css/custom.css
